from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.StockInstanceListView.as_view(), name='homepage'),
    re_path(r'^(?P<pk>\d+)$', views.StockInstanceDetailView.as_view(),
            name='stockInstance-detail'),
    path('create', views.StockInstanceCreate.as_view(),
         name='stockInstance-create'),
    re_path(r'^(?P<pk>\d+)/update/$',
            views.StockInstanceUpdate.as_view(), name='stockInstance-update'),
    re_path(r'^(?P<pk>\d+)/delete/$',
            views.StockInstanceDelete.as_view(), name='stockInstance-delete'),
    re_path(r'^stockfood/(?P<pk>\d+)/$',
            views.StockFoodDetail.as_view(), name='stockFood-detail'),
    re_path(r'^stockfood/create/(?P<pk>\d+)$',
            views.StockFoodCreate.as_view(), name='stockFood-create'),
    re_path(r'^stockfood/(?P<pk>\d+)/update/$',
            views.StockFoodUpdate.as_view(), name='stockFood-update'),
    re_path(r'^stockfood/(?P<pk>\d+)/delete/$',
            views.StockFoodDelete.as_view(), name='stockFood-delete'),
    path('foods', views.FoodListView.as_view(), name='all-foods'),
    re_path(r'^foods/(?P<pk>\d+)/$',
            views.FoodDetailView.as_view(), name='food-detail'),
    path('foods/create', views.FoodCreate.as_view(), name='food-create'),
    re_path(r'^foods/(?P<pk>\d+)/update/$',
            views.FoodUpdate.as_view(), name='food-update'),
    re_path(r'^foods/(?P<pk>\d+)/delete/$',
            views.FoodDelete.as_view(), name='food-delete'),
    path('recipes', views.RecipeListView.as_view(), name='all-recipes'),
    re_path(r'^recipe/(?P<pk>\d+)$',
            views.RecipeDetailView.as_view(), name='recipe-detail'),
    path('recipe/create/', views.RecipeCreate.as_view(), name='recipe-create'),
    re_path(r'^recipe/(?P<pk>\d+)/update/$',
            views.RecipeUpdate.as_view(), name='recipe-update'),
    re_path(r'^recipe/(?P<pk>\d+)/delete/$',
            views.RecipeDelete.as_view(), name='recipe-delete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
