# Generated by Django 4.2.18 on 2025-01-22 19:26

from django.db import migrations, models
import inventory.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shelf_life', inventory.fields.TimeFrameField(help_text='Enter the number and timeframe (days/weeks/months/years), e.g. 4 weeks', max_length=10)),
                ('category', models.ManyToManyField(help_text='Enter the foods category e.g(milk)', to='inventory.category')),
            ],
        ),
    ]
