# Generated by Django 4.2.18 on 2025-01-27 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import inventory.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(help_text='Enter the category type e.g (keto,vegan)', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Enter summary on category type: e.g(vegan: health benefits, environmental impact)')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shelf_life', inventory.fields.TimeFrameField(help_text='Enter the number and timeframe (days/weeks/months/years), e.g. 4 weeks', max_length=10)),
                ('category', models.ManyToManyField(help_text='Enter the foods category e.g(milk)', to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='StockInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x104af1940>stockroom', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Enter the expiry_date if known', null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.food')),
                ('stock_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockinstance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('category_type'), name='Category_category_type_case_insensitive_unique', violation_error_message='Category already exsists (case insensitive match)'),
        ),
    ]
