# Generated by Django 4.2.18 on 2025-01-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(db_index=True, help_text='Enter the category type e.g (keto,vegan)', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='stockinstance',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x102831730>stockroom', max_length=200),
        ),
    ]
