# Generated by Django 4.2.18 on 2025-01-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinstance',
            name='name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x1034196a0>stockroom', max_length=200),
        ),
    ]
