# Generated by Django 4.2.18 on 2025-02-04 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_alter_stockinstance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfood',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='Enter the expiry date (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='stockinstance',
            name='name',
            field=models.CharField(default='stockroom', max_length=200),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('portion_size', models.CharField(blank=True, choices=[('g', 'grams'), ('kg', 'kilograms'), ('oz', 'ounces'), ('ml', 'milliliters')], default='g', help_text='Enter the measurement for portion of recipe', max_length=2)),
                ('portion_quantity', models.PositiveSmallIntegerField(default=250)),
                ('instructions', models.TextField(help_text='Enter a clear concise method for making this recipe.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(help_text='Enter the dietary category e.g Vegan, Gluten Free', to='inventory.category')),
                ('ingredients', models.ManyToManyField(help_text='Enter the recipes ingredients', to='inventory.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
