# Generated by Django 4.2.18 on 2025-02-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_food_user_food_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='verified',
            field=models.BooleanField(null=True),
        ),
    ]
