# Generated by Django 4.2.18 on 2025-06-23 22:19

from django.db import migrations, models
import inventory.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_food_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfood',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='shelf_life',
            field=inventory.fields.TimeFrameField(help_text='Shelf life is optional , e.g. 4 weeks', max_length=35),
        ),
    ]
