# Generated by Django 4.2.18 on 2025-06-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stockfood_expired_alter_food_shelf_life'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockfood',
            name='expired',
        ),
    ]
