# Generated by Django 4.2.18 on 2025-07-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_stockfood_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.CharField(default='https://unsplash.com', max_length=400),
            preserve_default=False,
        ),
    ]
