# Generated by Django 4.2.18 on 2025-07-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
